---
# https://taskfile.dev
version: '3'
env:
  RENDER_DIR: .rendered
  AGENT: base
tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list
    silent: true
  render-template:
    desc: "Render template"
    cmds:
      - echo "Rendering template"
      - copier copy . ./$RENDER_DIR/agent_$AGENT --defaults
      - cp ./fixtures/Taskfile.yml ./$RENDER_DIR/agent_$AGENT/Taskfile.yml
      - cp ./fixtures/infra/pyproject.toml ./$RENDER_DIR/agent_$AGENT/infra/pyproject.toml
      - cp ./fixtures/infra/__init__.py ./$RENDER_DIR/agent_$AGENT/infra/infra/__init__.py
  install-dev:
    desc: "Install dev"
    cmds:
      - task: render-template
      - echo "Installing dev"
      - task: render-template
      - task agent_test:agent:install --dir $RENDER_DIR/agent_$AGENT
  test:
    desc: "Run tests"
    cmds:
      - task: install-dev
      - echo "Running tests"
      - task agent_test:agent:lint-check --dir $RENDER_DIR/agent_$AGENT
      - task agent_test:agent:test-coverage --dir $RENDER_DIR/agent_$AGENT
