pipeline:
  name: E2E tests
  identifier: E2E_tests
  projectIdentifier: afcomponentagent
  orgIdentifier: buzok
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-agent
        build: <+input>
        prCloneStrategy: SourceBranch
        sparseCheckout: []
  stages:
    - parallel:
        - stage:
            name: Run E2E tests - LangGraph
            identifier: Run_E2E_tests_LangGraph
            description: "Run af-component-agent E2E tests for LangGraph agent"
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: false
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run LangGraph E2E
                      identifier: run_langgraph_e2e
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: ubuntu:latest
                        shell: Bash
                        command: |-
                          set -xe

                          export DATAROBOT_ENDPOINT="<+pipeline.variables.DATAROBOT_ENDPOINT>"
                          export DATAROBOT_API_TOKEN="<+pipeline.variables.DATAROBOT_API_TOKEN>"
                          export E2E_AGENT_FRAMEWORKS="langgraph"

                          apt update -q
                          apt install -q -y curl git build-essential python3-dev

                          curl -LsSf https://astral.sh/uv/install.sh | sh
                          export PATH="${HOME}/.local/bin:${PATH}"
                          uv python install 3.11

                          curl -L https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.deb -o task.deb
                          dpkg -i task.deb

                          RUN_E2E=1 uv run --all-extras pytest --import-mode=importlib -vv -s ./tests/e2e/test_agent_e2e.py
        - stage:
            name: Run E2E tests - NAT
            identifier: Run_E2E_tests_NAT
            description: "Run af-component-agent E2E tests for NAT agent"
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: false
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run NAT E2E
                      identifier: run_nat_e2e
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: ubuntu:latest
                        shell: Bash
                        command: |-
                          set -xe

                          export DATAROBOT_ENDPOINT="<+pipeline.variables.DATAROBOT_ENDPOINT>"
                          export DATAROBOT_API_TOKEN="<+pipeline.variables.DATAROBOT_API_TOKEN>"
                          export E2E_AGENT_FRAMEWORKS="nat"

                          apt update -q
                          apt install -q -y curl git build-essential python3-dev

                          curl -LsSf https://astral.sh/uv/install.sh | sh
                          export PATH="${HOME}/.local/bin:${PATH}"
                          uv python install 3.11

                          curl -L https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.deb -o task.deb
                          dpkg -i task.deb

                          RUN_E2E=1 uv run --all-extras pytest --import-mode=importlib -vv -s ./tests/e2e/test_agent_e2e.py
        - stage:
            name: Run E2E tests - CrewAI
            identifier: Run_E2E_tests_CrewAI
            description: "Run af-component-agent E2E tests for CrewAI agent"
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: false
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run CrewAI E2E
                      identifier: run_crewai_e2e
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: ubuntu:latest
                        shell: Bash
                        command: |-
                          set -xe

                          export DATAROBOT_ENDPOINT="<+pipeline.variables.DATAROBOT_ENDPOINT>"
                          export DATAROBOT_API_TOKEN="<+pipeline.variables.DATAROBOT_API_TOKEN>"
                          export E2E_AGENT_FRAMEWORKS="crewai"

                          apt update -q
                          apt install -q -y curl git build-essential python3-dev

                          curl -LsSf https://astral.sh/uv/install.sh | sh
                          export PATH="${HOME}/.local/bin:${PATH}"
                          uv python install 3.11

                          curl -L https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.deb -o task.deb
                          dpkg -i task.deb

                          RUN_E2E=1 uv run --all-extras pytest --import-mode=importlib -vv -s ./tests/e2e/test_agent_e2e.py
        - stage:
            name: Run E2E tests - LlamaIndex
            identifier: Run_E2E_tests_LlamaIndex
            description: "Run af-component-agent E2E tests for LlamaIndex agent"
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: false
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run LlamaIndex E2E
                      identifier: run_llamaindex_e2e
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: ubuntu:latest
                        shell: Bash
                        command: |-
                          set -xe

                          export DATAROBOT_ENDPOINT="<+pipeline.variables.DATAROBOT_ENDPOINT>"
                          export DATAROBOT_API_TOKEN="<+pipeline.variables.DATAROBOT_API_TOKEN>"
                          export E2E_AGENT_FRAMEWORKS="llamaindex"

                          apt update -q
                          apt install -q -y curl git build-essential python3-dev

                          curl -LsSf https://astral.sh/uv/install.sh | sh
                          export PATH="${HOME}/.local/bin:${PATH}"
                          uv python install 3.11

                          curl -L https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.deb -o task.deb
                          dpkg -i task.deb

                          RUN_E2E=1 uv run --all-extras pytest --import-mode=importlib -vv -s ./tests/e2e/test_agent_e2e.py
        - stage:
            name: Run E2E tests - Base
            identifier: Run_E2E_tests_Base
            description: "Run af-component-agent E2E tests for base agent"
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: false
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run Base E2E
                      identifier: run_base_e2e
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: ubuntu:latest
                        shell: Bash
                        command: |-
                          set -xe

                          export DATAROBOT_ENDPOINT="<+pipeline.variables.DATAROBOT_ENDPOINT>"
                          export DATAROBOT_API_TOKEN="<+pipeline.variables.DATAROBOT_API_TOKEN>"
                          export E2E_AGENT_FRAMEWORKS="base"

                          apt update -q
                          apt install -q -y curl git build-essential python3-dev

                          curl -LsSf https://astral.sh/uv/install.sh | sh
                          export PATH="${HOME}/.local/bin:${PATH}"
                          uv python install 3.11

                          curl -L https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.deb -o task.deb
                          dpkg -i task.deb

                          RUN_E2E=1 uv run --all-extras pytest --import-mode=importlib -vv -s ./tests/e2e/test_agent_e2e.py
  variables:
    - name: DATAROBOT_ENDPOINT
      type: String
      description: "DataRobot API endpoint (e.g. https://staging.datarobot.com/api/v2)"
      required: true
      value: <+input>
    - name: DATAROBOT_API_TOKEN
      type: String
      description: "DataRobot API token with permissions to create custom models and deployments"
      required: true
      value: <+input>
  timeout: 60m
