name: 'render copier instance'
description: 'Creates default copier instances using copier and task'
inputs:
  working-directory:
    description: 'Working directory to run commands in'
    required: false
    default: '.'
  copier-args:
    description: 'Arguments to pass to copier copy command'
    required: false
    default: '--defaults'
runs:
  using: 'composite'
  steps:
    - name: render copier instance
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git config --global --add safe.directory /__w/af-component-agent/af-component-agent
        apt update --allow-releaseinfo-change && apt install -y git g++ --no-install-recommends
        mkdir -p ./rendered/.datarobot/answers/
        cp ./fixtures/.datarobot/answers/llm-llm.yml ./rendered/.datarobot/answers/llm-llm.yml
        uvx copier copy . ./rendered ${{ inputs.copier-args }}
        cp ./fixtures/infra/pyproject.toml ./rendered/infra/pyproject.toml
        cp ./fixtures/infra/__init__.py ./rendered/infra/infra/__init__.py
        cd ./rendered