pipeline:
  name: ci_checks
  identifier: ci_checks
  projectIdentifier: afcomponentagent
  orgIdentifier: No_Code_Apps
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-agent
        build: <+input>
  stages:
    - stage:
        name: linter
        identifier: linter
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: build environment
                  identifier: build_environment
                  spec:
                    connectorRef: account.GHCR
                    image: astral-sh/uv:python3.11-bookworm
                    shell: Sh
                    command: |-
                      sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

                      task --version
                    envVariables:
                      PYTHON_VERSION: "3.11"
