pipeline:
  name: ci_checks
  identifier: ci_checks
  projectIdentifier: afcomponentagent
  orgIdentifier: No_Code_Apps
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-agent
        build: <+input>
  stages:
    - stage:
        name: linter
        identifier: linter
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: build environment
                  identifier: build_environment
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: python:3.11
                    shell: Bash
                    command: |-
                      set -exuo pipefail

                      apt-get update && apt upgrade -y
                      apt-get install -y gcc g++ python3-dev
                      apt-get clean

                      curl -LsSf https://astral.sh/uv/install.sh | sh
                      sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

                      export PATH="$PATH:/root/.local/bin"
                      export PATH="$PATH:/harness/bin"

                      uv version
                      task --version
                      git --version

                      uvx copier copy . ./copier_context --defaults
                      cp ./fixtures/Taskfile.yml ./copier_context/Taskfile.yml
                      cp ./fixtures/infra/pyproject.toml ./copier_context/infra/pyproject.toml
                      cp ./fixtures/infra/__init__.py ./copier_context/infra/infra/__init__.py

                      cd ./copier_context
                      task agent_test:agent:install
                    privileged: true
                    envVariables:
                      PYTHON_VERSION: "3.11"
