pipeline:
  name: Component Docker Test
  identifier: component_docker_test
  projectIdentifier: afcomponentagent
  orgIdentifier: No_Code_Apps
  tags: {}
  stages:
    - stage:
        name: Docker Prod Build and Test
        identifier: Docker_Prod_Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: false
            paths: []
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Background
                  name: start docker in docker
                  identifier: start_docker_in_docker
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: docker:dind
                    shell: Sh
                    privileged: true
                    resources:
                      limits:
                        memory: 4G
              - step:
                  type: Run
                  name: wait for docker in docker
                  identifier: wait_for_docker_in_docker
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: docker:24.0-cli
                    shell: Sh
                    command: |-
                      while ! docker ps ;do
                          echo "Docker not available yet"
                          sleep 1
                      done
                      echo "Docker Service Ready"
                      docker ps
                  timeout: 1m
              - step:
                  type: GitClone
                  name: clone codebase
                  identifier: clone_codebase
                  spec:
                    connectorRef: account.svc_harness_git1
                    repoName: af-component-agent
                    cloneDirectory: /harness/af-component-agent
                    build:
                      type: tag
                      spec:
                        tag: <+trigger.branch>
              - step:
                  type: Run
                  name: build image
                  identifier: build_image
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: docker:24.0-cli
                    shell: Sh
                    command: |-
                      cd af-component-agent
                      ls -la
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          sharedPaths:
            - /var/run
            - /var/lib/docker
