pipeline:
  name: Docker
  identifier: Docker
  projectIdentifier: afcomponentagent
  orgIdentifier: No_Code_Apps
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-agent
        build: <+input>
  stages:
    - stage:
        name: Docker Prod Build and Test
        identifier: Docker_Prod_Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Docker Prod Build and Test
                  identifier: Docker_Prod_Build_and_Test
                  spec:
                    shell: Sh
                    command: |-
                      # DockerHub login
                      echo "${DOCKERHUB_TOKEN}" | docker login --username datarobotread2 --password-stdin

                      # Building docker image
                      cd template/{{agent_app_name}}/docker_context/
                      docker build -f Dockerfile.prod . -t docker_context_prod
                    envVariables:
                      DOCKERHUB_TOKEN: <+secrets.getValue("account.dockerhubdatarobotread2orgread1")>
                  timeout: 10m
