pipeline:
  name: Harness PR Tests
  identifier: harness_pr_tests
  projectIdentifier: afcomponentagent
  orgIdentifier: No_Code_Apps
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-agent
        build: <+input>
  stages:
    - stage:
        name: ci_checks
        identifier: ci_checks
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: copier
                  identifier: copier
                  spec:
                    connectorRef: account.GHCR
                    image: astral-sh/uv:python3.12-bookworm
                    shell: Sh
                    command: |-
                      apt-get update
                      apt-get install -y --no-install-recommends git go-task

                      ls -la
                      uvx copier copy . ./copier_context --defaults
                      cp ./fixtures/Taskfile.yml ./copier_context/Taskfile.yml
                      cp ./fixtures/infra/pyproject.toml ./copier_context/infra/pyproject.toml
                      cp ./fixtures/infra/__init__.py ./copier_context/infra/infra/__init__.py
                      cd ./copier_context

                      go-task agent_test:agent:req
