pipeline:
  name: Test af-component-agent
  identifier: Build_af_component_agent_1752223405520
  projectIdentifier: afcomponentagent
  orgIdentifier: buzok
  stages:
    - stage:
        name: Test Component Base
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies and copy with copier
                  identifier: Install_dependencies_and_copy_with_copier
                  spec:
                    connectorRef: GHCR_HHI
                    image: ghcr.io/astral-sh/uv:python3.11-alpine
                    shell: Sh
                    command: |-
                      apk add git
                      uvx copier copy . ./copier_context --defaults
                      cp ./fixtures/Taskfile.yml ./copier_context/Taskfile.yml
                      cp ./fixtures/infra/pyproject.toml ./copier_context/infra/pyproject.toml
                      cp ./fixtures/infra/__init__.py ./copier_context/infra/infra/__init__.py
                    envVariables:
                      UV_CACHE_DIR: /.uv_cache
              - step:
                  type: Run
                  name: Base Linter and Unit Tests
                  identifier: Base_Linter_and_Unit_Tests
                  spec:
                    shell: Sh
                    connectorRef: GHCR_HHI
                    image: ghcr.io/astral-sh/uv:python3.11-alpine
                    command: |-
                      cd ./copier_context
                      uvx task agent_test:agent:req
                      uvx task task agent_test:agent:lint-check
                      uvx task agent_test:agent:test-coverage
                    envVariables:
                      UV_CACHE_DIR: /.uv_cache
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: true
            paths:
              - /.uv_cache
          buildIntelligence:
            enabled: true
          sharedPaths:
            - /.uv_cache
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: af-component-agent
        build: <+input>
        sparseCheckout: []
