name: 'Create Docker Context'
description: 'Creates docker context using task agent:create-docker-context'
inputs:
  working-directory:
    description: 'Working directory to run commands in'
    required: false
    default: '.'
  rendered-directory:
    description: 'Directory containing the rendered copier instance'
    required: false
    default: './rendered'
runs:
  using: 'composite'
  steps:
    - name: Create docker context
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if command -v uvx >/dev/null 2>&1 && [ -w /var/lib/apt/lists ]; then
          # Running in container with uvx available, execute directly
          cd ${{ inputs.rendered-directory }}
          uvx --from go-task-bin task agent:create-docker-context
        else
          # Running on host, use docker container
          docker run --rm -v "$(pwd):/workspace" -w /workspace ghcr.io/astral-sh/uv:python3.11-bookworm bash -c "
            cd ${{ inputs.rendered-directory }}
            uvx --from go-task-bin task agent:create-docker-context
          "
        fi