---
# https://taskfile.dev
version: '3'
vars:
  CLI: uv run cli.py
tasks:
  req:
    desc: 🛠️ Update local dependencies
    cmds:
      - echo "Updating local dependencies"
      - uv sync --all-extras
      - uv pip install git+https://github.com/datarobot-forks/litellm@mattn/add-datarobot-support-to-litellm
      - cd custom_model && uv pip install -r requirements.txt
    silent: true
  lint:
    desc: 🧹 Lint the codebase
    cmds:
      - echo "Linting the codebase"
      - uv run ruff check . --fix
      - uv run ruff format .
      - uv run mypy --pretty .
      - uv run yamlfix custom_model
    silent: true
  lint-check:
    desc: 🧹 Check whether the codebase is linted
    cmds:
      - echo "Checking linting"
      - uv run ruff format --check --diff .
      - uv run ruff check --diff .
      - uv run mypy --pretty .
    silent: true
  test:
    desc: 🧪 Run tests
    cmds: [echo "Running pytest on tests", uv run pytest -vv ./tests/]
    silent: true
  fix-licenses:
    desc: 📜 Fix license headers
    cmds:
      - echo "Fixing licenses"
      - cp ../.github/.licenserc.yaml ./
      - docker run  --rm -v {{.TASKFILE_DIR}}:/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:785bb7f3810572d6912666b4f64bad28e4360799
        -v info -c .licenserc.yaml header fix
      - rm ./.licenserc.yaml
    silent: true
  cli:
    desc: Run the CLI with provided arguments
    cmds:
      - echo "Running CLI {{.CLI_ARGS}}"
      - uv run cli.py {{.CLI_ARGS}}
    silent: true
