[project]
name = "infra"
version = "0.0.1"
description = """
This is a template for DataRobot Agents.
"""
requires-python = ">=3.11"

dependencies = [
    "datarobot-pulumi-utils>=0.1.8",
    "pulumi>=3.261.0",
    "pulumi-datarobot>=0.11.3",
    "jinja2>=3.1.6,<4.0",
    "pytz>=2026.3" # Temporary fix for datarobot pandas issue
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=7.1.0",
    "pytest>=9.1.1",
    "mypy>=2.3.1",
    "ruff>=0.16.6",
    "types-PyYAML>=6.0.12.20260906"
]
