---
name: Test af-component-agent Frameworks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test-crewai:
    name: "Test Component CrewAI"
    runs-on: "ubuntu-latest"
    container:
      image: ghcr.io/astral-sh/uv:${{ matrix.python }}-bookworm
    strategy:
      matrix:
        python: [python3.10, python3.11, python3.12]
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Render copier instance
        uses: ./.github/actions/render-copier-instance
        with:
          copier-args: '--defaults --data agent_app_name=agent_crewai --data agent_template_framework=crewai --data base_answers_file=.datarobot/answers/base.yml'
      - name: Install dependencies
        shell: sh
        run: |
          cd ./rendered/agent_crewai
          uvx --from go-task-bin task install
        env:
          UV_CACHE_DIR: /.uv_cache
      - name: Run linter
        shell: sh
        run: |
          cd ./rendered/agent_crewai
          uvx --from go-task-bin task lint-check
        env:
          UV_CACHE_DIR: /.uv_cache
      - name: Run unit tests
        shell: sh
        run: |
          cd ./rendered/agent_crewai
          uvx --from go-task-bin task test-coverage
        env:
          UV_CACHE_DIR: /.uv_cache