---
name: Component Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  uvx-copier-test:
    name: "UVX Copier Test"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Create Copier Template
        run: |
          uvx copier copy . ./copier_context --defaults
