---
name: Component - Infra
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: .
jobs:
  uvx-copier-infra-tests:
    name: Base Infra Linter and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Dependencies
        run: |
          uvx copier copy . ./copier_context --defaults
          cp ./fixtures/Taskfile.yml ./copier_context/Taskfile.yml
          cp ./fixtures/infra/Pulumi.yaml ./copier_context/infra/Pulumi.yaml
          cp ./fixtures/infra/pyproject.toml ./copier_context/infra/pyproject.toml
          cp ./fixtures/infra/__init__.py ./copier_context/infra/infra/__init__.py
          
          cd ./copier_context
          cd ./infra
          uv sync --all-extras --all-groups --dev
      - name: Lint Infra Template
        run: |
          cd ./copier_context
          cd ./infra
          uv run ruff format --check --diff .
          uv run ruff check --diff .
          uv run mypy --pretty .
      - name: Run unit tests
        run: |
          cd ./copier_context
          cd ./infra
          export PULUMI_CONFIG_PASSPHRASE=123
          pulumi login --local
          pulumi stack init -s organization/unittest/unittest
          uv run pytest -vv --cov --cov-report=html --cov-report=term --cov-report xml:.coverage.xml ./tests/
