---
name: Component Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  uvx-copier-copy-test:
    name: "Base Copier Test"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Dependencies
        run: |
          uvx copier copy . ./copier_context --defaults
  uvx-copier-lint-test:
    name: "Base Linter"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Dependencies
        run: |
          uvx copier copy . ./copier_context --defaults
          cd ./copier_context/agent
          task req
      - name: Lint Template
        run: task lint-check
  uvx-copier-unit-test:
    name: "Base Unit Tests"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Dependencies
        run: |
          uvx copier copy . ./copier_context --defaults
          cd ./copier_context/agent
          task req
      - name: Run unit tests
        run: task test
  uvx-copier-cli-test:
    name: "Base CLI Tests"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Dependencies
        run: |
          uvx copier copy . ./copier_context --defaults
          cd ./copier_context/agent
          task req
      - name: Run cli test
        run: |
          task cli -- execute --user_prompt '{"topic": "Artificial Intelligence"}'
          if task cli -- execute --user_prompt '{"topic": "Artificial Intelligence"}' | grep -q '"content": "success"'; then
            echo "Test passed: cli.py returned success"
          else
            echo "Test failed: cli.py did not return success"
            exit 1
          fi
