---
name: Component Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  uvx-copier-copy-test:
    name: "Base Copier Test"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Create Copier Template
        run: |
          uvx copier copy . ./copier_context --defaults
  uvx-copier-lint-test:
    name: "Base Linter"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Create Copier Template
        run: |
          uvx copier copy . ./copier_context --defaults
      - name: Lint Template
        run: |
          cd ./copier_context/agent
          task req
          task lint
  uvx-copier-unit-test:
    name: "Base Unit Tests"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Create Copier Template
        run: |
          uvx copier copy . ./copier_context --defaults
      - name: Lint Template
        run: |
          cd ./copier_context/agent
          task req
          task test
