---
name: Docker

on:
  push:
    branches: ["main"]
    paths:
      - 'template/{{agent_app_name}}/docker_context/*'

  pull_request:
    branches: ["main"]
    paths:
      - 'template/{{agent_app_name}}/docker_context/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: template/{{agent_app_name}}

jobs:
  hadolint:
    name: "Lint Dockerfiles"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
  docker-build-test:
    name: "Docker Public Build and Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Build Docker Image
        run: |
          cd docker_context
          docker build . -t docker_context
